export const LANG_RU_NAME = 'RU';


export const LANG_RU_TRANS = {
  // welcome
  'Welcome': 'Добро пожаловать в наш уютный и дружелюбный хостел',
  'Choose': 'Пожалуйста, выбери',
  'wantRoom': 'Я хочу комнату',
  'haveRoom': 'У меня есть бронь',

  // page-header
  'Back': 'Назад',

  // page-footer
  'Cancel': 'Отмена',

  // instructions
  'Instructions': 'инструкции',
  'prepare': 'Пожалуйста, подготовьте:',
  'creditCard': 'Кредитная карта - для оплаты',
  'btnNextInstructions': 'Хорошо, давайте найдем комнату',
  'willReceive': 'Для входа в свою комнату и общежитие вы получите',
  'pin': 'ПИН КОД',
  'remember': 'Обязательно запомните это.',
  'dataEmail': 'Кроме того, если вы предоставите нам адрес электронной почты или номер мобильного телефона, мы можем отправить вам информацию о вашем бронировании по электронной почте и/или SMS.',
  'invoiceEmail': 'Мы также можем отправить вам счет - фактуру по электронной почте.',

  //dates
  'Check-in and check-out': 'Регистрация заезда и отъезда',
  'when': 'Когда вы хотите забронировать номер?',
  'checkIn': 'Регистрироваться',
  'checkOut': 'Проверять, выписываться',
  // 'btnNextDates': 'Сохранить и пойти к гостям',
  'btnNextDates': 'Save and Select Persons',

  //persons
  'Persons': 'лиц',
  'guestsNumber': 'Введите число гостей',
  'adults': 'Взрослые',
  'children': 'Дети',
  'btnNextPersons': 'Сохранить и найти комнату',

  //choose room
  'chooseRoom': 'Choose Room',
  'Choose room': 'Выберите комнату',
  'Choose your room': 'Выберите комнату (нажмите на название)',
  'noRoomError': 'К сожалению, нет места для дат и количества гостей. Пожалуйста, вернитесь и выберите другие даты!',
  'imageClick': 'Нажмите на изображение, чтобы просмотреть подробную информацию и галерею',
  'noSelection': 'Пожалуйста, выберите категорию номера!',
  'buttonChooseRoomOK': 'Сохранить и перейти к информации о гостях',
  'buttonChooseRoomNoRoom': 'Перейти к датам',
  'GoBacktoRoomCategories': 'Go Back to Room Categories',
  'night': 'ночь',
  'page': 'страница',
  'of': 'из',

  // guests details
  'Guests': 'Детали гостей',
  'NextPayment': 'Сохранить и перейти к оплате',
  'NextNoPayment': 'Сохранить и перейти к завершению',
  'enterGuestsDetails': 'Введите данные гостей:',
  'noAllGuestsData': 'Пожалуйста, введите все данные гостя!',
  'firstName': 'Имя',
  'lastName': 'Фамилия',
  'idNo': 'ID или номер паспорта',
  'address': 'Адрес',
  'postCode': 'Почтовый индекс',
  'city': 'город',
  'country': 'Страна',
  'optional': '(Дополнительно, но рекомендуется). Мы можем отправить вам ваши данные о бронировании и / или счет-фактуру',
  'email': 'Адрес электронной почты (для информации о бронировании и / или счета-фактуры)',
  'mobile': 'Мобильный (для информации о бронировании)',
  'TermsAndConditions': 'Terms And Conditions',

  // company details
  'Company': 'Данные компании',
  'enterCompanyDetails': 'Введите данные о компании:',
  'noAllCompanyData': 'Пожалуйста, введите все данные компании!',
  'companyName': 'Название компании',
  'companyVatId': 'Код плательщика НДС',
  'companyAddress': 'Адрес',
  'companyPostCode': 'Почтовый индекс',
  'companyCity': 'город',
  'companyCountry': 'Страна',
  'companyOptional': '(Дополнительно, но рекомендуется).Мы можем отправить вам ваши данные о бронировании и/или счет-фактуру',
  'companyEmail': 'Адрес электронной почты (для информации о бронировании и/или счета-фактуры)',
  'companyMobile': 'Мобильный (для информации о бронировании)',
  'btnNextCompany': 'Сохранить и вернуться к оплате',
  'selectLang': 'Выбрать',

  // payment
  'Payment': 'Детали оплаты',
  'paymentDetails': 'Введите данные платежа',
  'noPaymentData': 'Пожалуйста, введите все необходимые данные оплаты!',
  'billToCompany': 'Билл для компании',
  'yes': 'да',
  'no': 'нет',
  'invoiceByEmail': 'Счет-фактура по электронной почте',
  'to': 'в',
  'nameCard': 'Имя на карточке',
  'numberCard': 'Номер карты',
  'expDate': 'Срок годности',
  'cvv': 'CVV',
  'btnNextPayment': 'Заплатите и идите, чтобы закончить',

  //finish
  'Finish': 'Детали бронирования',
  'successfully': 'Вы успешно бронируете номер!',
  'thankYou': 'Спасибо. Мы желаем вам приятного отдыха!',
  'importantInfo': 'Важная информация о вашем бронировании указана правильно. Пожалуйста, запомните это или запишите.',
  'weCanSend': 'Мы также можем отправить эту информацию по электронной почте и/или смс.',
  'sendByEmail': 'Отправить данные бронирования по электронной почте',
  'sendBySMS': 'Отправка данных бронирования по SMS',
  'yourPIN': 'Ваш ПИН-код :',
  'withYourPIN': 'С помощью ПИН-кода вы можете ввести:',
  'yourRoom': 'Ваш номер',
  'findRoom': 'Вы можете найти его на',
  'btnNextCloseUp': 'Конец',
  'sendMail':'Отправить письмо',

  // reservation
  'Reservation': 'Введите код брони',
  'enterCode': 'Введите код брони',
  'noCode': 'Пожалуйста, введите код бронирования!',
  'noReservation': 'Мы не можем найти бронирование с помощью этого кода.Пожалуйста, проверьте свой код!',
  'reservationCode': 'Код бронирования',
  'btnNextReservation': 'Найти бронирование',
  //scanning
  'Scanning': 'Scanning ID',
  'nextScanning': 'Next',

  //signing
  'Signing': 'Sign',
  'nextSigning': 'Sigature',
  'startScaning': 'Start Scanning',
  'pinRecovery': 'Pin Recovery',
  // Instruction Text
  'instruction_prepare': 'Please prepare',
  'instruction_payment': 'For Payment - Credit Card or EC Card',
  'instruction_id': 'For Identification  - Your Passport',
  'instruction_pin_one': 'For Entering your room and the main door you will recieve ',
  'instruction_pin_two': '6 Pin Number | 7 Pin Number | RoomCard Key',
  'instruction_pin_three': 'Be sure to remmeber it.',
  'instruction_provide_email': 'We provide also an email with the roomcode inside. We need for sure your e-mailadress.',
  'instruction_send_email': 'By that we send the bill to you by e-mail.',
  'instruction_send_message': 'If you add a whatsapp mobile nbr we will send y code.',
  'your_booking_code': 'Your Booking Code is : ',
  'boxPin': 'Your Box Pin is : ',
  'request_pin_recovery': 'Request For Pin',
  'booking_password': 'Booking Password',
  'enterPinRecoveryDetails': 'Enter Pin Recovery Details',
  'bookingNumber': 'Booking Number',
  'roomNumber': 'Room Number',
  'bookingPassword': 'Booking Password',
  'booking_password_recovery': 'Password for Recover Door Code',
  'noAllPinRecoveryData': 'Please Enter All Required Pin Recovery Data',
  'recovered_booking_pin': 'Your Booking Pin is : ',
  'booking_you_can_enter_text': 'You can enter the building through : ',

  //choose category
  'chooseCategory': 'Choose Category',
  'choose your category': 'choose your category :',
  'showRooms': 'Show Rooms',
  'buttonChooseCategoryOK': 'Save and Select Room',
  'termsAndConditions': 'Terms And Conditions',
  'i_accept': 'I ACCEPT',
  'NextSigning': 'Save and go to Signing',
  'NextScaning': 'Save and go to Scaning',
  'checkInDateReq' : 'Check In and Out Date Required',
  'you_booked_from' : 'You booked from ',
  'booked_to' : ' to',
  'error_reservation_1' : 'UnKnown Error',
  'error_reservation_2' : 'UnKnown Command',
  'error_reservation_3' : 'In sufficent Data',
  'error_reservation_4' : 'No Data',
  'error_reservation_5' : 'Not Connected',
  'error_reservation_6' : 'Already Connected',
  'error_reservation_7' : 'Can not reach',
  'error_reservation_8' : 'No Encoder',
  'error_reservation_9' : 'Room not free',
  'error_reservation_10' : 'Payment Unsuccessful',
  'error_reservation_11' : 'Not Allowed',
  'error_reservation_12' : 'Wrong Password',
  'error_terms_and_conditions' : 'Please accept terms and conditions',
  'please_accept' : 'Please Accept',
  'out_of_order' : 'Out Of Order',
  'text_all_right_reserver' : 'All Rights Reserved',
  'text_loading' : 'Loading...',
  'text_mail_sent' : 'Mail Sent Successfully',
  'text_mail_sent_error' : 'Mail Sent Failed'
};
