export const LANG_FR_NAME = 'FR';


export const LANG_FR_TRANS = {
  // welcome
  'Welcome': 'Bienvenue dans notre auberge confortable et conviviale',
  'Choose': "S'il vous plaît choisir",
  'wantRoom': 'Je veux une chambre',
  'haveRoom': "J'ai une réservation",

  // page-header
  'Back': 'Arrière',

  // page-footer
  'Cancel': 'Annuler',

  // instructions
  'Instructions': 'Instructions',
  'prepare': "S'il vous plaît préparer:",
  'creditCard': 'Carte de crédit - pour paiement',
  'btnNextInstructions': 'OK, permet de trouver une chambre',
  'willReceive': 'Pour entrer dans votre chambre et votre auberge, vous recevrez',
  'pin': 'CODE PIN',
  'remember': 'Assurez-vous de vous en souvenir.',
  'dataEmail': 'De plus, si vous nous fournissez une adresse e-mail ou un numéro de portable, nous pouvons vous envoyer des informations sur votre réservation par e-mail et / ou par SMS.',
  'invoiceEmail': 'Nous pouvons également vous envoyer une facture par e-mail.',

  //dates
  'Check-in and check-out': 'Check-in et check-out',
  'when': 'Quand souhaitez- vous réserver une chambre?',
  'checkIn': 'Enregistrement',
  'checkOut': 'Check-out',
  // 'btnNextDates': 'Enregistrer et aller aux invités',
  'btnNextDates': 'Save and Select Persons',

  //persons
  'Persons': 'Personnes',
  'guestsNumber': "Entrez le nombre d'invités",
  'adults': 'Adultes',
  'children': 'Enfants',
  'btnNextPersons': 'Enregistrer et trouver une chambre',

  //choose room
  'chooseRoom': 'Choose Room',
  'Choose room': 'Choisissez une chambre',
  'Choose your room': 'Choisissez votre chambre (cliquez sur le nom)',
  'noRoomError': "Malheureusement, il n'y a pas de place pour les dates et le nombre d'invités.S'il vous plaît, revenez en arrière et choisissez d'autres dates!",
  'imageClick': "Cliquez sur l'image pour voir les détails et la galerie",
  'noSelection': "S'il vous plaît, sélectionnez la catégorie de chambre!",
  'buttonChooseRoomOK': 'Enregistrer et aller aux détails des clients',
  'buttonChooseRoomNoRoom': 'Aller aux dates',
  'GoBacktoRoomCategories': 'Go Back to Room Categories',
  'night': 'nuit',
  'page': 'Page',
  'of': 'de',

  // guests details
  'Guests': 'Les détails des clients',
  'NextPayment': 'Enregistrer et aller au paiement',
  'NextNoPayment': 'Sauvez et partez pour finir',
  'enterGuestsDetails': 'Entrez les détails des invités:',
  'noAllGuestsData': "S'il vous plaît, entrez toutes les données d'invité requises!",
  'firstName': 'Prénom',
  'lastName': 'Nom de famille',
  'idNo': "Numéro d'identification ou de passeport",
  'address': 'Adresse',
  'postCode': 'Code postal',
  'city': 'Ville',
  'country': 'Pays',
  'optional': '(Facultatif mais recommandé) Nous pouvons vous envoyer vos détails de réservation et/ou facture',
  'email': 'Adresse e- mail(pour les détails de réservation et/ou facture)',
  'mobile': 'Mobile (pour les détails de la réservation)',
  'TermsAndConditions': 'Terms And Conditions',

  // company details
  'Company': 'Les données de la compagnie',
  'enterCompanyDetails': 'Entrez les détails de la société:',
  'noAllCompanyData': "S'il vous plaît, entrez toutes les données de l'entreprise requises!",
  'companyName': 'Nom de la compagnie',
  'companyVatId': 'Identifiant de TVA',
  'companyAddress': 'Adresse',
  'companyPostCode': 'Code postal',
  'companyCity': 'Ville',
  'companyCountry': 'Pays',
  'companyOptional': '(Facultatif mais recommandé) Nous pouvons vous envoyer vos détails de réservation et/ou facture',
  'companyEmail': 'Adresse e- mail(pour les détails de réservation et / ou facture)',
  'companyMobile': 'Mobile (pour les détails de la réservation)',
  'btnNextCompany': 'Enregistrer et retourner au paiement',
  'selectLang': 'Sélectionner',

  // payment
  'Payment': 'Détails de paiement',
  'paymentDetails': 'Entrer les détails du paiement',
  'noPaymentData': 'Veuillez entrer toutes les données de paiement requises!',
  'billToCompany': 'Facturer à la compagnie',
  'yes': 'Oui',
  'no': 'Non',
  'invoiceByEmail': 'Facture par e-mail',
  'to': 'à',
  'nameCard': 'Nom sur la Carte',
  'numberCard': 'Numéro de carte',
  'expDate': "Date d'expiration",
  'cvv': 'CVV',
  'btnNextPayment': 'Payer et aller à la fin',

  //finish
  'Finish': 'Les détails de réservation',
  'successfully': 'Vous avez réussi à réserver une chambre!',
  'thankYou': 'Merci.Nous vous souhaitons un agréable séjour!',
  'importantInfo': "Les informations importantes concernant votre réservation sont indiquées à droite. S'il vous plaît, souvenez-vous - en ou notez- le.",
  'weCanSend': 'Nous pouvons également envoyer cette information par e-mail et/ou sms.',
  'sendByEmail': 'Envoyer les données de réservation par e-mail',
  'sendBySMS': 'Envoyer des données de réservation par SMS',
  'yourPIN': 'Votre code PIN est :',
  'withYourPIN': 'Avec votre code PIN, vous pouvez entrer:',
  'yourRoom': 'Votre chambre est',
  'findRoom': 'Vous pouvez le trouver sur',
  'btnNextCloseUp': 'Terminer',
  'sendMail':'Envoyer un mail',


  // reservation
  'Reservation': 'Entrez votre code de réservation',
  'enterCode': 'Entrez votre code de réservation',
  'noCode': "S'il vous plaît, entrez le code de réservation!",
  'noReservation': "Nous ne pouvons pas trouver de réservation avec ce code.S'il vous plaît, vérifiez votre code!",
  'reservationCode': 'Code de réservation',
  'btnNextReservation': 'Trouver une réservation',
  //scanning
  'Scanning': 'Scanning ID',
  'nextScanning': 'Next',

  //signing
  'Signing': 'Sign',
  'nextSigning': 'Sigature',
  'startScaning': 'Start Scanning',
  'pinRecovery': 'Pin Recovery',
  // Instruction Text
  'instruction_prepare': 'Please prepare',
  'instruction_payment': 'For Payment - Credit Card or EC Card',
  'instruction_id': 'For Identification  - Your Passport',
  'instruction_pin_one': 'For Entering your room and the main door you will recieve ',
  'instruction_pin_two': '6 Pin Number | 7 Pin Number | RoomCard Key',
  'instruction_pin_three': 'Be sure to remmeber it.',
  'instruction_provide_email': 'We provide also an email with the roomcode inside. We need for sure your e-mailadress.',
  'instruction_send_email': 'By that we send the bill to you by e-mail.',
  'instruction_send_message': 'If you add a whatsapp mobile nbr we will send y code.',
  'your_booking_code': 'Your Booking Code is : ',
  'boxPin': 'Your Box Pin is : ',
  'request_pin_recovery': 'Request For Pin',
  'booking_password': 'Booking Password',
  'enterPinRecoveryDetails': 'Enter Pin Recovery Details',
  'bookingNumber': 'Booking Number',
  'roomNumber': 'Room Number',
  'bookingPassword': 'Booking Password',
  'booking_password_recovery': 'Password for Recover Door Code',
  'noAllPinRecoveryData': 'Please Enter All Required Pin Recovery Data',
  'recovered_booking_pin': 'Your Booking Pin is : ',
  'booking_you_can_enter_text': 'You can enter the building through : ',

  //choose category
  'chooseCategory': 'Choose Category',
  'choose your category': 'choose your category :',
  'showRooms': 'Show Rooms',
  'buttonChooseCategoryOK': 'Save and Select Room',
  'termsAndConditions': 'Terms And Conditions',
  'i_accept': 'I ACCEPT',
  'NextSigning': 'Save and go to Signing',
  'NextScaning': 'Save and go to Scaning',
  'checkInDateReq' : 'Check In and Out Date Required',
  'you_booked_from' : 'You booked from ',
  'booked_to' : ' to',
  'error_reservation_1' : 'UnKnown Error',
  'error_reservation_2' : 'UnKnown Command',
  'error_reservation_3' : 'In sufficent Data',
  'error_reservation_4' : 'No Data',
  'error_reservation_5' : 'Not Connected',
  'error_reservation_6' : 'Already Connected',
  'error_reservation_7' : 'Can not reach',
  'error_reservation_8' : 'No Encoder',
  'error_reservation_9' : 'Room not free',
  'error_reservation_10' : 'Payment Unsuccessful',
  'error_reservation_11' : 'Not Allowed',
  'error_reservation_12' : 'Wrong Password',
  'error_terms_and_conditions' : 'Please accept terms and conditions',
  'please_accept' : 'Please Accept',
  'out_of_order' : 'Out Of Order',
  'text_all_right_reserver' : 'All Rights Reserved',
  'text_loading' : 'Loading...',
  'text_mail_sent' : 'Mail Sent Successfully',
  'text_mail_sent_error' : 'Mail Sent Failed'
};
