export const LANG_ES_NAME = 'ES';


export const LANG_ES_TRANS = {
  // welcome
  'Welcome': 'Bienvenido a nuestro acogedor y acogedor albergue',
  'Choose': 'Por favor elige',
  'wantRoom': 'Quiero una habitación',
  'haveRoom': 'Tengo una reservación',

  // page-header
  'Back': 'Espalda',

  // page-footer
  'Cancel': 'Cancelar',

  // instructions
  'Instructions': 'Instrucciones',
  'prepare': 'Porfavor prepara:',
  'creditCard': 'Tarjeta de crédito - para pago',
  'btnNextInstructions': 'OK, vamos a buscar una habitación',
  'willReceive': 'Para ingresar a su habitación y albergue, recibirá',
  'pin': 'NÚMERO DE PIN',
  'remember': 'Asegúrate de recordarlo.',
  'dataEmail': 'Además, si nos proporciona su dirección de correo electrónico o número de teléfono móvil, podemos enviarle información sobre su reserva por correo electrónico y / o SMS.',
  'invoiceEmail': 'También podemos enviarle una factura por correo electrónico.',


  //dates
  'Check-in and check-out': 'Check-in y check-out',
  'when': 'Cuándo quieres reservar habitación?',
  'checkIn': 'Registrarse',
  'checkOut': 'Revisa',
  // 'btnNextDates': 'Guarde y vaya a los invitados',
  'btnNextDates': 'Save and Select Persons',

  //persons
  'Persons': 'Personas',
  'guestsNumber': 'Ingrese el número de invitados',
  'adults': 'Adultos',
  'children': 'Niños',
  'btnNextPersons': 'Guarde y encuentre una habitación',

  //choose room
  'chooseRoom': 'Choose Room',
  'Choose room': 'Elige habitación',
  'Choose your room': 'Elige tu habitación (haga clic en el nombre)',
  'noRoomError': 'Desafortunadamente, no hay espacio para fechas determinadas y número de invitados.Por favor, regresa y elige otras fechas!',
  'imageClick': 'Haga clic en la imagen para ver los detalles y la galería',
  'noSelection': 'Por favor, selecciona la categoría de habitación!',
  'buttonChooseRoomOK': 'Guarde y vaya a los detalles de los invitados',
  'buttonChooseRoomNoRoom': 'Ir a las fechas',
  'GoBacktoRoomCategories': 'Go Back to Room Categories',
  'night': 'noche',
  'page': 'Page',
  'of': 'of',

  // guests details
  'Guests': 'Detalles de los invitados',
  'NextPayment': 'Guarde e ingrese al pago',
  'NextNoPayment': 'Guarde y vaya a terminar',
  'enterGuestsDetails': 'Ingrese los detalles de los invitados:',
  'noAllGuestsData': 'Por favor, ingrese todos los datos requeridos.',
  'firstName': 'Nombre de pila',
  'lastName': 'Apellido',
  'idNo': 'ID o número de pasaporte',
  'address': 'Dirección',
  'postCode': 'Código postal',
  'city': 'Ciudad',
  'country': 'País',
  'optional': '(Opcional pero recomendado) Podemos enviarle los detalles de su reserva y/o factura',
  'email': 'Dirección de correo electrónico (para detalles de la reserva y/o factura)',
  'mobile': 'Móvil (para detalles de reserva)',
  'TermsAndConditions': 'Terms And Conditions',

  // company details
  'Company': 'Datos de la compañia',
  'enterCompanyDetails': 'Ingrese los detalles de la compañía:',
  'noAllCompanyData': 'Por favor, ingrese todos los datos requeridos de la compañía!',
  'companyName': 'Nombre de empresa',
  'companyVatId': 'ID de IVA',
  'companyAddress': 'Dirección',
  'companyPostCode': 'Código postal',
  'companyCity': 'Ciudad',
  'companyCountry': 'País',
  'companyOptional': '(Opcional pero recomendado) Podemos enviarle los detalles de su reserva y / o factura',
  'companyEmail': 'Dirección de correo electrónico (para detalles de la reserva y / o factura)',
  'companyMobile': 'Móvil (para detalles de reserva)',
  'btnNextCompany': 'Guarde y regrese al pago',
  'selectLang': 'Seleccionar',

  // payment
  'Payment': 'Detalles del pago',
  'paymentDetails': 'Ingrese los detalles del pago',
  'noPaymentData': 'Por favor, ingrese todos los datos de pago requeridos!',
  'billToCompany': 'Proyecto de ley a compañía',
  'yes': 'Sí',
  'no': 'No',
  'invoiceByEmail': 'Factura por correo electrónico',
  'to': 'a',
  'nameCard': 'Nombre en la Tarjeta',
  'numberCard': 'Número de tarjeta',
  'expDate': 'Fecha de caducidad',
  'cvv': 'CVV',
  'btnNextPayment': 'Pagar e ir a terminar',

  //finish
  'Finish': 'Detalles de la reserva',
  'successfully': 'Has reservado una habitación con éxito!',
  'thankYou': 'Gracias! Te deseamos una estancia agradable!',
  'importantInfo': 'La información importante sobre su reserva se enumeran a la derecha.Por favor, recuérdalo o escríbelo.',
  'weCanSend': 'También podemos enviar esta información por correo electrónico y / o sms.',
  'sendByEmail': 'Enviar los datos de reserva por correo electrónico',
  'sendBySMS': 'Enviar datos de reserva por SMS',
  'yourPIN': 'Su número PIN es :',
  'withYourPIN': 'Con su PIN puede ingresar:',
  'yourRoom': 'Tu habitación es',
  'findRoom': 'Puedes encontrarlo en',
  'btnNextCloseUp': 'Terminar',
  'sendMail':'Enviar correo',

  // reservation
  'Reservation': 'Ingrese su código de reserva',
  'enterCode': 'Ingrese su código de reserva',
  'noCode': 'Por favor, ingrese el código de reserva!',
  'noReservation': 'No podemos encontrar reserva con este código.Por favor, revisa tu código!',
  'reservationCode': 'Código de reservación',
  'btnNextReservation': 'Buscar reserva',
  //scanning
  'Scanning': 'Scanning ID',
  'nextScanning': 'Next',

  //signing
  'Signing': 'Sign',
  'nextSigning': 'Sigature',
  'startScaning': 'Start Scanning',
  'pinRecovery': 'Pin Recovery',
  // Instruction Text
  'instruction_prepare': 'Please prepare',
  'instruction_payment': 'For Payment - Credit Card or EC Card',
  'instruction_id': 'For Identification  - Your Passport',
  'instruction_pin_one': 'For Entering your room and the main door you will recieve ',
  'instruction_pin_two': '6 Pin Number | 7 Pin Number | RoomCard Key',
  'instruction_pin_three': 'Be sure to remmeber it.',
  'instruction_provide_email': 'We provide also an email with the roomcode inside. We need for sure your e-mailadress.',
  'instruction_send_email': 'By that we send the bill to you by e-mail.',
  'instruction_send_message': 'If you add a whatsapp mobile nbr we will send y code.',
  'your_booking_code': 'Your Booking Code is : ',
  'boxPin': 'Your Box Pin is : ',
  'request_pin_recovery': 'Request For Pin',
  'booking_password': 'Booking Password',
  'enterPinRecoveryDetails': 'Enter Pin Recovery Details',
  'bookingNumber': 'Booking Number',
  'roomNumber': 'Room Number',
  'bookingPassword': 'Booking Password',
  'booking_password_recovery': 'Password for Recover Door Code',
  'noAllPinRecoveryData': 'Please Enter All Required Pin Recovery Data',
  'recovered_booking_pin': 'Your Booking Pin is : ',
  'booking_you_can_enter_text': 'You can enter the building through : ',

  //choose category
  'chooseCategory': 'Choose Category',
  'choose your category': 'choose your category :',
  'showRooms': 'Show Rooms',
  'buttonChooseCategoryOK': 'Save and Select Room',
  'termsAndConditions': 'Terms And Conditions',
  'i_accept': 'I ACCEPT',
  'NextSigning': 'Save and go to Signing',
  'NextScaning': 'Save and go to Scaning',
  'checkInDateReq' : 'Check In and Out Date Required',
  'you_booked_from' : 'You booked from ',
  'booked_to' : ' to',
  'error_reservation_1' : 'UnKnown Error',
  'error_reservation_2' : 'UnKnown Command',
  'error_reservation_3' : 'In sufficent Data',
  'error_reservation_4' : 'No Data',
  'error_reservation_5' : 'Not Connected',
  'error_reservation_6' : 'Already Connected',
  'error_reservation_7' : 'Can not reach',
  'error_reservation_8' : 'No Encoder',
  'error_reservation_9' : 'Room not free',
  'error_reservation_10' : 'Payment Unsuccessful',
  'error_reservation_11' : 'Not Allowed',
  'error_reservation_12' : 'Wrong Password',
  'error_terms_and_conditions' : 'Please accept terms and conditions',
  'please_accept' : 'Please Accept',
  'out_of_order' : 'Out Of Order',
  'text_all_right_reserver' : 'All Rights Reserved',
  'text_loading' : 'Loading...',
  'text_mail_sent' : 'Mail Sent Successfully',
  'text_mail_sent_error' : 'Mail Sent Failed'
};
