export const LANG_EN_NAME = 'EN';

export const LANG_EN_TRANS = {
  //welcome
  'Welcome': 'Welcome to our cozy and friendly Hostel',
  'Choose': 'Please choose',
  'wantRoom': 'I want a room',
  'haveRoom': 'I have a reservation',

  // page-header
  'Back': 'Back',

  // page-footer
  'Cancel': 'Cancel',

  // instructions
  'Instructions': 'Instructions',
  'prepare': 'Please prepare:',
  'creditCard': 'Credit card - for payment',
  'btnNextInstructions': 'OK, lets find a room',
  'willReceive': 'For entering your room and hostel you will receive',
  'pin': 'PIN NUMBER',
  'remember': 'Be sure to remember it.',
  'dataEmail': 'Also, if you provide us e-mail address or mobile number, we can send you information about your booking by e-mail and/or SMS.',
  'invoiceEmail': 'We can also send you invoice by e-mail.',

  //dates
  'Check-in and check-out': 'Check-in and check-out',
  'when': 'When would you like to book room?',
  'checkIn': 'Check-in',
  'checkOut': 'Check-out',
  'btnNextDates': 'Save and Select Persons',

  //persons
  'Persons': 'Persons',
  'guestsNumber': 'Enter number of guests',
  'adults': 'Adults',
  'children': 'Children',
  'btnNextPersons': 'Save and find a room',

  //choose room
  'chooseRoom' : 'Choose Room',
  'Choose room': 'Choose room',
  'Choose your room': 'Choose your room (click on room name)',
  'noRoomError': 'Unfortunately, there is no room for given dates and number of guests. Please, go back and choose other dates!',
  'imageClick': 'Click on image to see details and gallery',
  'noSelection': 'Please, select room category!',
  'buttonChooseRoomOK': 'Save and go to guest details',
  'buttonChooseRoomNoRoom': 'Go to dates',
  'GoBacktoRoomCategories': 'Go Back to Room Categories', 
  'night': 'night',
  'page': 'Page',
  'of': 'of',

  // guests details
  'Guests': 'Guests details',
  'NextPayment': 'Save and go to payment',
  'NextNoPayment': 'Save and go to finish',
  'enterGuestsDetails': 'Enter guests details:',
  'noAllGuestsData': 'Please, enter all required guest data!',
  'firstName': 'First name',
  'lastName': 'Last name',
  'idNo': 'ID or Passport number',
  'address': 'Address',
  'postCode': 'Post code',
  'city': 'City',
  'country': 'Country',
  'optional': '(Optional but recommended) We can send you your booking details and/or invoice',
  'email': 'E-mail address (for booking details and/or invoice)',
  'mobile': 'Mobile (for booking details)',
  'TermsAndConditions': 'Terms And Conditions',


  // company details
  'Company': 'Company data',
  'enterCompanyDetails': 'Enter company details:',
  'noAllCompanyData': 'Please, enter all required company data!',
  'companyName': 'Company name',
  'companyVatId': 'VAT ID',
  'companyAddress': 'Address',
  'companyPostCode': 'Post code',
  'companyCity': 'City',
  'companyCountry': 'Country',
  'companyOptional': '(Optional but recommended) We can send you your booking details and/or invoice',
  'companyEmail': 'E-mail address (for booking details and/or invoice)',
  'companyMobile': 'Mobile (for booking details)',
  'btnNextCompany': 'Save and return to payment',
  'selectLang': 'Select',

  // payment
  'Payment': 'Payment details',
  'paymentDetails': 'Enter payment details',
  'noPaymentData': 'Please, enter all required payment data!',
  'billToCompany': 'Bill to company',
  'yes': 'Yes',
  'no': 'No',
  'invoiceByEmail': 'Invoice by e-mail',
  'to': 'to',
  'nameCard': 'Name on the card',
  'numberCard': 'Card number',
  'expDate': 'Expiration date',
  'cvv': 'CVV',
  'btnNextPayment': 'Pay and go to finish',

  //finish
  'Finish': 'Booking details',
  'successfully': 'You successfully book a room!',
  'thankYou': 'Thank you.We wish you a pleasant stay!',
  'importantInfo': 'Important information about your booking are listed right. Please, remember it or write it down.',
  'weCanSend': 'We can also send this information by e-mail and/or sms.',
  'sendByEmail': 'Send booking data by e-mail',
  'sendBySMS': 'Send booking data by SMS',
  'yourPIN': 'Your PIN number is :',
  'withYourPIN': 'With your PIN you can enter:',
  'yourRoom': 'Your room is',
  'findRoom': 'You can find it on',
  'btnNextCloseUp': 'Finish',
  'sendMail':'Send EMail',

  // reservation
  'Reservation': 'Enter your reservation code',
  'enterCode': 'Enter your reservation code',
  'noCode': 'Please, enter reservation code!',
  'noReservation': 'We cannot find reservation with this code. Please, check your code!',
  'reservationCode': 'Reservation code',
  'btnNextReservation': 'Find reservation',

  //scanning
  'Scanning': 'Scanning ID',
  'nextScanning': 'Next',

  //signing
  'Signing': 'Sign',
  'nextSigning': 'Sigature',
  'startScaning': 'Start Scanning',
  'pinRecovery': 'Pin Recovery',
  // Instruction Text
  'instruction_prepare': 'Please prepare',
  'instruction_payment': 'For Payment - Credit Card or EC Card',
  'instruction_id': 'For Identification  - Your Passport',
  'instruction_pin_one': 'For Entering your room and the main door you will recieve ',
  'instruction_pin_two': '6 Pin Number | 7 Pin Number | RoomCard Key',
  'instruction_pin_three': 'Be sure to remmeber it.',
  'instruction_provide_email': 'We provide also an email with the roomcode inside. We need for sure your e-mailadress.',
  'instruction_send_email': 'By that we send the bill to you by e-mail.',
  'instruction_send_message': 'If you add a whatsapp mobile nbr we will send y code.',
  'your_booking_code': 'Your Booking Code is : ',
  'boxPin': 'Your Box Pin is : ',
  'request_pin_recovery': 'Request For Pin',
  'booking_password': 'Booking Password',
  'enterPinRecoveryDetails': 'Enter Pin Recovery Details',
  'bookingNumber': 'Booking Number',
  'roomNumber': 'Room Number',
  'bookingPassword': 'Booking Password',
  'booking_password_recovery': 'Password for Recover Door Code',
  'noAllPinRecoveryData': 'Please Enter All Required Pin Recovery Data',
  'recovered_booking_pin': 'Your Booking Pin is : ',
  'booking_you_can_enter_text': 'You can enter the building through : ',

  //choose category
  'chooseCategory': 'Choose Category', 
  'choose your category': 'Choose Your Category :',
  'showRooms' : 'Show Rooms',
  'buttonChooseCategoryOK' : 'Save and Select Room',
  'termsAndConditions' : 'Terms And Conditions',
  'i_accept' : 'I ACCEPT',
  'NextSigning': 'Save and go to Signing',
  'NextScaning': 'Save and go to Scaning',
  'checkInDateReq' : 'Check In and Out Date Required',
  'you_booked_from' : 'You booked from ',
  'booked_to' : ' to',
  'error_reservation_1' : 'UnKnown Error',
  'error_reservation_2' : 'UnKnown Command',
  'error_reservation_3' : 'In sufficent Data',
  'error_reservation_4' : 'No Data',
  'error_reservation_5' : 'Not Connected',
  'error_reservation_6' : 'Already Connected',
  'error_reservation_7' : 'Can not reach',
  'error_reservation_8' : 'No Encoder',
  'error_reservation_9' : 'Room not free',
  'error_reservation_10' : 'Payment Unsuccessful',
  'error_reservation_11' : 'Not Allowed',
  'error_reservation_12' : 'Wrong Password',
  'error_terms_and_conditions' : 'Please accept terms and conditions',
  'please_accept' : 'Please Accept',
  'out_of_order' : 'Out Of Order',
  'text_all_right_reserver' : 'All Rights Reserved',
  'text_loading' : 'Loading...',
  'text_mail_sent' : 'Mail Sent Successfully',
  'text_mail_sent_error' : 'Mail Sent Failed'
};
